spring.application.name=jobapi
spring.datasource.url=jdbc:mysql://localhost:3306/jobapi
spring.datasource.username=root
spring.datasource.password=Neena@86

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true